"""add commit_author, commit_date and contributors to code_block

Revision ID: 751d3213a853
Revises: d4e5f6a7b8c9
Create Date: 2026-03-18 11:09:56.342131
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '751d3213a853'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_block', sa.Column('commit_author', sa.String(length=100), nullable=True, comment='最后修改该代码块的作者'))
    op.add_column('code_block', sa.Column('commit_date', sa.DateTime(), nullable=True, comment='最后修改该代码块的时间'))
    op.add_column('code_block', sa.Column('contributors', sa.Text(), nullable=True, comment='JSON格式: [{"author": "张三", "commits": 10, "last_date": "2024-01-15"}, ...]'))
    op.alter_column('code_block', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment='pending / generated / success / failed',
               existing_comment='pending / success / failed',
               existing_nullable=False)
    op.alter_column('response_feedback', 'message_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='Feishu message_id of the answer card',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('response_feedback', 'message_id',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='Feishu message_id of the answer card',
               existing_nullable=False)
    op.alter_column('code_block', 'status',
               existing_type=mysql.VARCHAR(length=20),
               comment='pending / success / failed',
               existing_comment='pending / generated / success / failed',
               existing_nullable=False)
    op.drop_column('code_block', 'contributors')
    op.drop_column('code_block', 'commit_date')
    op.drop_column('code_block', 'commit_author')
    # ### end Alembic commands ###
