"""initial schema

Revision ID: d367df9ff585
Revises: 
Create Date: 2026-03-16 17:22:38.713029
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd367df9ff585'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id')
    )
    op.create_table('chat_kb_binding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('kb_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'kb_id', 'deleted_at', name='uk_chat_kb')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('sender_id', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('msg_type', sa.String(length=20), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('topic_group_id', sa.String(length=100), nullable=True),
    sa.Column('pending_count', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('idx_chat_processed', 'chat_message', ['chat_id', 'processed'], unique=False)
    op.create_index('idx_created', 'chat_message', ['created_at'], unique=False)
    op.create_index('idx_topic_group', 'chat_message', ['topic_group_id'], unique=False)
    op.create_table('chat_repo_binding',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'repo_id', 'deleted_at', name='uk_chat_repo')
    )
    op.create_table('chat_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('debug_mode', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('code_block',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('block_type', sa.String(length=20), nullable=False),
    sa.Column('block_name', sa.String(length=200), nullable=True),
    sa.Column('parent_class', sa.String(length=200), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('milvus_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_commit', 'code_block', ['commit_hash'], unique=False)
    op.create_index('idx_repo_file', 'code_block', ['repo_id', 'file_path'], unique=False)
    op.create_table('code_repo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('git_url', sa.String(length=500), nullable=False),
    sa.Column('kb_id', sa.BigInteger(), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('last_commit_hash', sa.String(length=64), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kb_type', sa.Enum('chat', 'code', 'manual', name='kb_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('milvus_collection', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('manual_knowledge',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=True),
    sa.Column('sender_id', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=True),
    sa.Column('sender_id', sa.String(length=100), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('block_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summarize_error_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.BigInteger(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summarize_task_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kb_id', sa.BigInteger(), nullable=False),
    sa.Column('task_type', sa.Enum('scheduled', 'manual', 'code', name='task_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='task_status_enum'), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('new_knowledge_count', sa.Integer(), nullable=True),
    sa.Column('updated_knowledge_count', sa.Integer(), nullable=True),
    sa.Column('deleted_knowledge_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summarize_task_log')
    op.drop_table('summarize_error_log')
    op.drop_table('security_log')
    op.drop_table('manual_knowledge')
    op.drop_table('knowledge_base')
    op.drop_table('code_repo')
    op.drop_index('idx_repo_file', table_name='code_block')
    op.drop_index('idx_commit', table_name='code_block')
    op.drop_table('code_block')
    op.drop_table('chat_settings')
    op.drop_table('chat_repo_binding')
    op.drop_index('idx_topic_group', table_name='chat_message')
    op.drop_index('idx_created', table_name='chat_message')
    op.drop_index('idx_chat_processed', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('chat_kb_binding')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
