"""add code_block status and content_hash columns

Revision ID: f0d67a5be465
Revises: d367df9ff585
Create Date: 2026-03-16 19:39:04.850406
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d67a5be465'
down_revision: Union[str, None] = 'd367df9ff585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_block', sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 of code content, used to detect changes'))
    op.add_column('code_block', sa.Column('status', sa.String(length=20), nullable=False, comment='pending / success / failed'))
    op.add_column('code_block', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index('idx_repo_status', 'code_block', ['repo_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_repo_status', table_name='code_block')
    op.drop_column('code_block', 'error_message')
    op.drop_column('code_block', 'status')
    op.drop_column('code_block', 'content_hash')
    # ### end Alembic commands ###
